### ISSUE TITLE
  console.log (`Kullanıcılar       : ${client.users.cache.size}`); çalışmıyor

### ISSUE THREAD

**Issue by Akif9748** [EmirhanSarac/discord-altyapi-bot#14]
`  console.log (`Kullanıcılar       : ${client.users.cache.size}`);` olması gerektiğinden daha az kişiyi gösteriyor

**Comment by KaffinPX** [comment]
cache diyor ztn malmısın

**Comment by Akif9748** [comment]
Yani? Yazamıyon değil mi? Ben çözdüm:
`
 let serverlist = ''        let count = 0; //&lt;---        client.guilds.cache.forEach((guild) =&gt; {        count += guild.memberCount // &lt;---     })`
